INSERT INTO `inventory` (name, count, actual_count) VALUES ('Laptop MSI', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Fotoaparat Canon', 1, null);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Monitor ', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Tlačiareň HP - stara', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('vlajka -  KUS', 3, 3);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Bim projektor', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Plátno pre projektor', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Reproduktory - veľké', 8, 6);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Reproduktory - malé', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('CD Prehrávač ', 1, );
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Mixážne pulty - Yamaha', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Zosilňovač', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Ovládač svetiel a stmievača', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('mikrofóny ', 9, 9);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('stojan na noty', 10, 10);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('reflektory', 20, 18);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Stojan na reproduktor', 4, 4);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('ohrievač - magitec', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('radiátor', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('tlačiareňa a scaner - HP - nový', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Kremenný ohrievač', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('chladnička - BIRA', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Varič - Sigma', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Skriňa - jednokrídlová', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Skriňa - dvojkrídolvá', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Stôl - veľký', 2, 2);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Stoličky - biele', 8, 8);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Rámy pre výstavu', 10, 9);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Bluetooth reproduktor', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Stará polica - rekvizit', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('hoklík - "stóvčoke"', 7, 7);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Akustický panel', 4, 4);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('stôl - starý', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('kontrabas', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('computer - starý', 2, 2);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('monitor - starý', 2, 2);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('kyjake', 12, 12);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Reflektor - duble ', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Reflektor ', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Kulisne', 1, 1);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Stojan na refletory', 2, 2);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Prijimač pre mikrofón', 2, 2);
INSERT INTO `inventory` (name, count, actual_count) VALUES ('Taška za laptop', 1, 1);
